feat(ImageManager): add --job-retention-policy flag to the controller
senthilrch/kube-fledged pull request #160
Opened 2022-04-12 16:55 UTC by niladrih

Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>

This PR adds the '--job-retention-policy' flag to the controller. Possible values for this flag are 'delete' and 'retain'.

delete behavior:
- Delete Image Manager jobs after a Job status is acquired by the lister.

retain behavior:
- Leave Image Manager jobs in the cluster after a Job status is acquired by the lister.

2022-04-12 16:57 UTC, niladrih commented
I've built and tested on k8s 1.23.3 (linux/arm64)
@senthilrch PTAL. Thanks.

2022-04-13 11:33 UTC, senthilrch requested changes

2022-04-13 11:33 UTC, senthilrch commented on README.md
> +`--job-retention-policy:` Set if an Image Manager Kubernetes Job API object will be deleted or retained (for debugging) after it finishes. Possible values are 'delete' and 'retain', defaults to 'dele
Please rephrase as below:-
`--job-retention-policy:` Determines if the jobs created by kubefledged-controller would be deleted or retained (for debugging) after it finishes. Possible values are 'delete' and 'retain'. default value is 'delete'.

2022-04-13 11:33 UTC, senthilrch commented on deploy/kubefledged-operator/helm-charts/kubefledged/README.md
> +| args.controllerJobRetentionPolicy | "delete" | Set Job delete/retain behavior of controller after a Job finishes |
Please rephrase as below:-
Determines if the jobs created by kubefledged-controller would be deleted or retained (for debugging) after it finishes. Possible values are 'delete' and 'retain'. default value is 'delete'.

2022-04-13 11:33 UTC, senthilrch commented on docs/helm-parameters.md
> +| args.controllerJobRetentionPolicy | "delete" | Set Job delete/retain behavior of controller after a Job finishes |
Please rephrase as below:-
Determines if the jobs created by kubefledged-controller would be deleted or retained (for debugging) after it finishes. Possible values are 'delete' and 'retain'. default value is 'delete'.

2022-04-13 13:47 UTC, niladrih commented
@senthilrch -- Made the changes. PTAL. Thanks

2022-04-13 13:52 UTC, senthilrch approved these changes

2022-04-13 14:02 UTC, merged